# Generated by Django 3.1.3 on 2020-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='Display Name', max_length=256),
            preserve_default=False,
        ),
    ]
