# Generated by Django 3.1.3 on 2020-11-27 23:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201127_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
