# Generated by Django 3.1.3 on 2020-11-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_algorithm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
